name: flow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Patch Gitea
        run: |
          git clone https://github.com/go-gitea/gitea.git
          cd gitea
          git apply ../oauth.go.patch

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./gitea
          file: ./gitea/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/gitea:${{ github.sha }}
            ghcr.io/${{ github.repository }}/gitea:latest
